lang: zh_CN
initial:
  skillPoint: 10
basic:
  #玩家是否只能选择一次职业
  onlyOnce: true
  magic:
    full: 200
    refillRate: 5
    refillValue: 10

#圣谕
c1:
  s1:
  #治愈
    skillPoint:
      #解锁所需技能点
      unlock: 1
      #升级所需技能点
      upgrade: 2
    release:
      #释放技能所需法力值
      magic: 5
      #冷却时间
      cooldown: 2
    #技能最大值
    maxlevel: 7
  s2:
    skillPoint:
      unlock: 2
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s3:
    skillPoint:
      unlock: 3
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s4:
    skillPoint:
      unlock: 5
      upgrade: 3
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
c2:
  s1:
    skillPoint:
      unlock: 1
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s2:
    skillPoint:
      unlock: 2
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s3:
    skillPoint:
      unlock: 3
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s4:
    skillPoint:
      unlock: 5
      upgrade: 3
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
c3:
  s1:
    skillPoint:
      unlock: 1
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s2:
    skillPoint:
      unlock: 2
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s3:
    skillPoint:
      unlock: 3
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s4:
    skillPoint:
      unlock: 5
      upgrade: 3
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
c4:
  s1:
    skillPoint:
      unlock: 1
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s2:
    skillPoint:
      unlock: 2
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s3:
    skillPoint:
      unlock: 3
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s4:
    skillPoint:
      unlock: 5
      upgrade: 3
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7

c5:
  s1:
    skillPoint:
      unlock: 1
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s2:
    skillPoint:
      unlock: 2
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s3:
    skillPoint:
      unlock: 3
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s4:
    skillPoint:
      unlock: 5
      upgrade: 3
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7

c6:
  s1:
    skillPoint:
      unlock: 1
    release:
      magic: 5
      cooldown: 2
      upgrade: 2
    maxlevel: 7
  s2:
    skillPoint:
      unlock: 2
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s3:
    skillPoint:
      unlock: 3
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s4:
    skillPoint:
      unlock: 5
      upgrade: 3
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
c7:
  s1:
    skillPoint:
      unlock: 1
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s2:
    skillPoint:
      unlock: 2
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s3:
    skillPoint:
      unlock: 3
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s4:
    skillPoint:
      unlock: 5
      upgrade: 3
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
c8:
  s1:
    skillPoint:
      unlock: 1
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s2:
    skillPoint:
      unlock: 2
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s3:
    skillPoint:
      unlock: 3
      upgrade: 2
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
  s4:
    skillPoint:
      unlock: 5
      upgrade: 3
    release:
      magic: 5
      cooldown: 2
    maxlevel: 7
